//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal_ASP.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int ApplicationId { get; set; }
        public int Candidate { get; set; }
        public int ListingId { get; set; }
    
        public virtual Listing Listing { get; set; }
        public virtual User User { get; set; }
    }
}
