//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal_ASP.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public Listing()
        {
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int ListingId { get; set; }
        public string ListingDescription { get; set; }
        public Nullable<System.DateTime> ListedDate { get; set; }
        public Nullable<double> GpaRequirement { get; set; }
        public Nullable<double> ExperienceRequirement { get; set; }
        public Nullable<int> OpenToAll { get; set; }
        public string ListingTitle { get; set; }
        public Nullable<double> AgeRequirement { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<JobApplication> JobApplications { get; set; }
        public virtual User User { get; set; }
    }
}
